### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by GrazingScientist** [django-cms/djangocms-column#54]
Could please make a new release. When I upgrade to Django 3.2.13, my pip complains that there is a conflict. From my current deduction, `djangocms_column` is causing this, because its version 1.11.0 only allows `django<=3.2`.

Best Regards,

Adrian

**Comment by marksweb** [comment]
Hi @GrazingScientist - I've just released 2.0

I've removed the upper limit on django because this is best coming from django-cms itself. Having it here as well just makes maintenance harder, as you've seen.

**Comment by GrazingScientist** [comment]
Thank you so much! 🥳
